Eclipse 3.7 updated some internal AST classes, causing: NoSuchMethodError: CastExpression.<init>
This commit fixes this (now lombok works both <3.7 and 3.7).

fixes issue #206